---

- hosts: smtpout
  become: yes
  gather_facts: True
  tasks:
  - name: restart SMG status
    command: "/opt/scripts/killsmg.sh"
    register: result
    ignore_errors: yes

  - name: showing report
    debug:
     var: result
