---

- hosts: all
  become: yes
  gather_facts: True
  tasks:
  #- name: checking service status
  #  command: "/etc/init.d/gwava7 status"
  #  register: result
  #  ignore_errors: yes
  - name: checking service status
    command: "free -h"

    register: result
    ignore_errors: yes
  

  - name: showing report
    debug:
     var: result
