---

- hosts: all
  become: yes
  gather_facts: True
  tasks:
  - name: run port_check
    command: "/vastorage/scripts/portcheck.sh"
    register: result
    ignore_errors: yes
#  - name: checking service status
#    command: "lsof -i TCP:25 | wc -l"
#    register: result
#    ignore_errors: yes
  

  - name: showing report
    debug:
     var: result
